export const FETCH_DRONS = 'FETCH_DRONS';
export const REQUEST_DRONS = 'REQUEST_DRONS';
export const ADD_PREVIEW = 'ADD_PREVIEW';
export const CHANGE_DRONS = 'CHANGE_DRONS';
export const SET_CURRENT_DRON = 'SET_CURRENT_DRON';
export const CHANGE_MODAL = 'CHANGE_MODAL';

export const SET_NAME_TEXT = 'VALIDATION/SET_NAME_TEXT';
export const SET_PHONE_NUMBER = 'VALIDATION/SET_PHONE_NUMBER';
export const CHECK_VALIDATION = 'VALIDATION/CHECK_VALIDATION';
export const CLEAR_VALIDATION = 'VALIDATION/CLEAR_VALIDATION';

export const SHOW_LOADER = 'SHOW_LOADER';
export const HIDE_LOADER = 'HIDE_LOADER';
export const SHOW_ERROR = 'SHOW_ERROR';
